### ISSUE TITLE
Updated code files and useful information

### ISSUE THREAD

**Issue by newaeonweb** [PacktPublishing/Hands-On-Full-Stack-Web-Development-with-Angular-6-and-Laravel-5#1]
Hi, please i suggest to you the following code samples: https://github.com/newaeonweb/Hands-On-Full-Stack-Web-Development-with-Angular-6-and-Laravel-5

If you prefer i can made a Pull-Request to this repository and we can keep the code updated. Just let me know.

**Comment by techsachinkumar** [comment]
Hi Fernando,

I have added you to this repository so that you can make the necessary changes to the code.
You can send a pull request as well so that we can merge it to this repository.

Regards.

**Comment by newaeonweb** [comment]
HI @techsachinkumar, great thanks!
