### ISSUE TITLE
Chapter 1 - 4: comments to use the book under windows. Issue with Swagger

### ISSUE THREAD

**Issue by Fuchssystems** [PacktPublishing/Hands-On-Full-Stack-Web-Development-with-Angular-6-and-Laravel-5#3]
Working with the .pdf version of the book on Windows 10 and found the following obstacles, which others might find helpful.

Excellent book, however feel the author should walk thru the steps under windows (issues see below).
For the moment stopped near end of chapter 4 after encountering the first show stopper that I could not fix (Swagger installation).
Possibly will resume later.

Chapter 1

Screen shot "PhpDocker interface"
Extensions: MySQL: "Memcached" not checked
I am running without the memcache container and it seems to work so far.

Creating a migrations file and database seed
"database/factories folder" folder: file "ModalFactory.php" does not exist.
Instead a file "BandFactory.php" has to be created inside the folder "factories".

Using the resource flag to create CRUD methods
"4. Add the following line, right after App\Http\Requests:"
"App\Http\Requests:" does not exist in this file.
Instead pasted
"use App\Http\Requests;
use App\Band;"
from the example code under line "use Illuminate\Http\Request;".

"5. Update the routes.php file, inside the routes folder, to the following code:"
The filename is not "routes.php", but "web.php".

Creating the Blade template engine
Step 4:
missing is the need to edit file "BandController.php": function "index":
"return view('bands.index', array('bands' => $bands));"

Chapter 2

Using Enum
Step 4: Output string "My favorite..." not in "console.log".

Chapter 3

Installing the Angular CLI
Step 3: "rm -rf node_modules"
Under windows, "rm" has no parameter "rf".

Command: "ng doc HttpClient":
Result:
"The doc command requires to be run in an Angular project, but a project definition could not be found."

Installing VS Code Angular plugins:
The last one "GitLens" is doubled ("This extension is extremly..." text is duplicated.

Creating a simple Angular application
Command "ng new chapter03 --routing": question "Which stylesheet...": missing in book text.
Did choose CSS

Environments
Command "ng build --env = prod"
"The build command requires to be run in an Angular project, but a project definition could not be found."
Using "chaper03" files from .zip archive: same error message.

Solution:
".angular-cli.json" must be named "angular.json".
The command to built is "np serve".

Tunning the sample application
"npm serve" includes "npm start"

Creating an Angular service
Code file "beers.service.ts"
"import { Observable } from 'rxjs/Observable';"
Compiler error: "src/app/beers/beers.service.ts(4,10): error TS2305: Module '"F:/Laravel-angular/chapter03/chapter03/node_modules/rxjs/Observable"' has no exported member 'Observable'."
Solved by command: "npm install --save rxjs-compat"

Simple deployment
Command "cd dist && http-server -p 8080":
"&&" not valid in windows
Directory must be subdirectory "chapter03".

Step 5: Command "git add .git commit -m "chapter03 initial commit"
Error: "unknown switch `m'".
Solved by seperating commands (error is that "-m" gets passed to the "add" command):
"git add ."
"git commit -m "chapter03 initial commit"

Chapter 4

Using PHP Composer to scaffold a Laravel application

Step 3: 3. We will see the following output on the Terminal:
Composer version 1.6.3
Output warning: "Do not run Composer as root/super user! See https://getcomposer.org/root for details"
Version is: "Composer version 1.8.4 2019-02-11 10:52:10"

Creating the application scaffold
Command "composer create-project laravel/laravel=5.6.12 project --prefer-dist"
The directory "project" is created inside another directory "project".
This seems to be an error, because "http://localhost:8081/" later results in "file not found".
Solution is to manually move the directoy "project" one level up ("chapter04/project/app...").

Creating our first database seed
Step 2: Sample data
In the .pdf file, the first "picture": URL is missing the closing quotation mark.

Installing the L5-Swagger library
Step 2: the line must be terminated with ",".
Step 3: before the command "php..." "php-fpm bash" is required:
"docker-compose exec php-fpm bash"

Command issues error:
In ProviderRepository.php line 208:
"Class 'L5Swagger\L5SwaggerServiceProvider' not found  "
Could not fix this.

Docker troubleshooting under Windows 10:
- Windows Professional required
- Virtualization has to be enabled in the BIOS
- In the Hyper-V manager console, a new virtual switch of type "extern" has to be created
- after that a reboot was required
- worked, however
- after Windows did update itself, docker commands failed.
- solution was that the Hyper-V service had to be set to be loaded automatically on windows startup. Set by a powershell command to automatic.

**Comment by andrew-svirin** [comment]
@Fuchssystems had some thing. Just check that in `composer.json` was added "darkaonline/l5-swagger"
